// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IpPV_OTmFD5Xzn6Op26v6FkfaWFww4o',
    appId: '1:537518650000:web:fa08e61cca9f25cfcb1e15',
    messagingSenderId: '537518650000',
    projectId: 'umeshweb-954c0',
    authDomain: 'umeshweb-954c0.firebaseapp.com',
    storageBucket: 'umeshweb-954c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB35M8rrGUWnOcyJ8hNKRaF75LL-ZqdjuI',
    appId: '1:537518650000:android:91dbb3ec723cf6e4cb1e15',
    messagingSenderId: '537518650000',
    projectId: 'umeshweb-954c0',
    storageBucket: 'umeshweb-954c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjhysaO_0Da_p0L1iAMVYBnQkXJPIH5M',
    appId: '1:537518650000:ios:021fce50a58b8c08cb1e15',
    messagingSenderId: '537518650000',
    projectId: 'umeshweb-954c0',
    storageBucket: 'umeshweb-954c0.appspot.com',
    iosBundleId: 'com.example.introAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjhysaO_0Da_p0L1iAMVYBnQkXJPIH5M',
    appId: '1:537518650000:ios:021fce50a58b8c08cb1e15',
    messagingSenderId: '537518650000',
    projectId: 'umeshweb-954c0',
    storageBucket: 'umeshweb-954c0.appspot.com',
    iosBundleId: 'com.example.introAppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1IpPV_OTmFD5Xzn6Op26v6FkfaWFww4o',
    appId: '1:537518650000:web:a169c787905dd24ccb1e15',
    messagingSenderId: '537518650000',
    projectId: 'umeshweb-954c0',
    authDomain: 'umeshweb-954c0.firebaseapp.com',
    storageBucket: 'umeshweb-954c0.appspot.com',
  );
}
